const fs = require('fs');
const path = require('path');

function esc(str) {
  return (str || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function writeProjectConfig(dir, values) {
  const dest = path.join(dir, 'src/config/project.js');
  fs.mkdirSync(path.dirname(dest), { recursive: true });

  const days = JSON.stringify(values.businessHours?.days || []);
  const langs = JSON.stringify(values.languages || ['en', 'es']);

  const content = `// Project Configuration
// Auto-generated by yarn setup. Re-run yarn setup to update.

export const PROJECT_CONFIG = {
  name: '${esc(values.projectName)}',
  description: '${esc(values.description)}',

  url: {
    production: '${esc(values.productionUrl)}',
    development: 'http://localhost:5173',
    staging: '${esc(values.stagingUrl || '')}',
  },

  organization: {
    name: '${esc(values.orgName)}',
    url: '${esc(values.productionUrl)}',
    logo: '${esc(values.productionUrl)}/logo.png',
    description: '${esc(values.description)}',
    contact: {
      email: '${esc(values.email)}',
      phone: '${esc(values.phone || '')}',
      address: '${esc(values.address || '')}',
      hours: {
        days: ${days},
        open: '${esc(values.businessHours?.open || '')}',
        close: '${esc(values.businessHours?.close || '')}',
      },
    },
    social: {
      twitter: '${esc(values.twitter || '')}',
      github: '${esc(values.github || '')}',
      linkedin: '${esc(values.linkedin || '')}',
      facebook: '${esc(values.facebook || '')}',
      instagram: '${esc(values.instagram || '')}',
    },
  },

  seo: {
    defaultTitle: '${esc(values.projectName)}',
    description: '${esc(values.description)}',
    keywords: [],
    author: '${esc(values.orgName)}',
    twitter: '${esc(values.twitter || '')}',
    image: '${esc(values.productionUrl)}/og-image.png',
  },

  pages: {
    home: {
      title: '${esc(values.orgName)}',
      description: '${esc(values.description)}',
      keywords: [],
      image: '${esc(values.productionUrl)}/og-image.png',
    },
    demo: {
      title: 'Component Demo | ${esc(values.projectName)}',
      description: 'Explore the component library. This page is for development only.',
      keywords: ['demo', 'components', 'ui', 'react'],
      image: '${esc(values.productionUrl)}/og-image.png',
    },
    notFound: {
      title: 'Page Not Found | ${esc(values.projectName)}',
      description: 'The page you are looking for does not exist.',
      noindex: true,
    },
  },

  analytics: {
    googleAnalyticsId: process.env.VITE_GA_ID || '',
    googleTagManagerId: process.env.VITE_GTM_ID || '',
    hotjarId: process.env.VITE_HOTJAR_ID || '',
    sentryDsn: process.env.VITE_SENTRY_DSN || '',
  },

  features: {
    analytics: process.env.NODE_ENV === 'production',
    demoMode: process.env.NODE_ENV === 'development',
    pwa: true,
    darkMode: true,
    errorReporting: process.env.NODE_ENV === 'production',
    performanceMonitoring: process.env.NODE_ENV === 'production',
  },

  security: {
    contentSecurityPolicy: process.env.NODE_ENV === 'production',
    httpsOnly: process.env.NODE_ENV === 'production',
    trustExternalScripts: false,
  },

  performance: {
    enableServiceWorker: true,
    enablePreloading: true,
    enableLazyLoading: true,
    enableCodeSplitting: true,
  },

  localization: {
    defaultLanguage: 'en',
    supportedLanguages: ${langs},
    dateFormat: 'MM/DD/YYYY',
    currency: 'USD',
    timezone: 'America/New_York',
  },

  ...getEnvOverrides(),
};

function getEnvOverrides() {
  const env = process.env.NODE_ENV || 'development';
  switch (env) {
    case 'production':
      return {
        features: { analytics: true, demoMode: false, pwa: true, darkMode: true, errorReporting: true, performanceMonitoring: true },
        security: { contentSecurityPolicy: true, httpsOnly: true, trustExternalScripts: false },
      };
    case 'development':
      return {
        features: { analytics: false, demoMode: true, pwa: true, darkMode: true, errorReporting: false, performanceMonitoring: false },
        security: { contentSecurityPolicy: false, httpsOnly: false, trustExternalScripts: true },
      };
    case 'test':
      return {
        features: { analytics: false, demoMode: false, pwa: true, darkMode: true, errorReporting: false, performanceMonitoring: false },
        security: { contentSecurityPolicy: false, httpsOnly: false, trustExternalScripts: false },
      };
    default:
      return {};
  }
}

export const getEnvConfig = () => PROJECT_CONFIG;
export const useProjectConfig = () => getEnvConfig();
export default PROJECT_CONFIG;
`;

  fs.writeFileSync(dest, content);
}

function writePackageJson(dir, values) {
  const pkgPath = path.join(dir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  pkg.name = values.projectName;
  pkg.description = values.description;
  pkg.version = values.version || '0.1.0';
  pkg.repository = values.repoUrl || '';
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
}

function writeEnvExample(dir, values) {
  const sentryHint = values.sentryDsn ? `\n# ${values.sentryDsn}` : '';
  const apiKeyHint = values.firebaseApiKey
    ? `\n# ${values.firebaseApiKey}`
    : '';
  const authDomainHint = values.firebaseAuthDomain
    ? `\n# ${values.firebaseAuthDomain}`
    : '';
  const projectIdHint = values.firebaseProjectId
    ? `\n# ${values.firebaseProjectId}`
    : '';
  const storageBucketHint = values.firebaseStorageBucket
    ? `\n# ${values.firebaseStorageBucket}`
    : '';
  const senderIdHint = values.firebaseMessagingSenderId
    ? `\n# ${values.firebaseMessagingSenderId}`
    : '';
  const appIdHint = values.firebaseAppId ? `\n# ${values.firebaseAppId}` : '';
  const gaHint = values.gaId ? `\n# ${values.gaId}` : '';

  const content = `# ============================================================
# ${values.projectName} - Environment Variables
# ============================================================
# Copy this file to .env and fill in your values.
# NEVER commit .env to source control.
#
# VITE_ prefix = exposed to browser (public, no secrets)
# No prefix    = server-side only (Netlify Functions, never public)
# ============================================================

# --- Frontend (browser-safe) ---
VITE_SENTRY_DSN=${sentryHint}
VITE_GA_ID=${gaHint}
VITE_GTM_ID=
VITE_HOTJAR_ID=
VITE_APP_ENV=development

# --- Firebase CMS (Optional) ---
VITE_CMS_ENABLED=false

# Firebase Configuration (get from Firebase Console > Project Settings)
VITE_FIREBASE_API_KEY=${apiKeyHint}
VITE_FIREBASE_AUTH_DOMAIN=${authDomainHint}
VITE_FIREBASE_PROJECT_ID=${projectIdHint}
VITE_FIREBASE_STORAGE_BUCKET=${storageBucketHint}
VITE_FIREBASE_MESSAGING_SENDER_ID=${senderIdHint}
VITE_FIREBASE_APP_ID=${appIdHint}
VITE_FIREBASE_MEASUREMENT_ID=

# --- Backend (Netlify Functions only) ---
# SENTRY_DSN=
# ALLOWED_ORIGIN=${values.productionUrl || 'https://yourproject.com'}
`;

  fs.writeFileSync(path.join(dir, '.env.example'), content);
}

function writeManifest(dir, values) {
  const dest = path.join(dir, 'public/manifest.json');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  const manifest = {
    name: values.orgName,
    short_name: values.projectName,
    start_url: '/',
    display: 'standalone',
    background_color: '#000000',
    theme_color: '#000000',
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  };
  fs.writeFileSync(dest, JSON.stringify(manifest, null, 2) + '\n');
}

function writeRobotsTxt(dir, values) {
  const dest = path.join(dir, 'public/robots.txt');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  const content = `User-agent: *
Allow: /

Sitemap: ${values.productionUrl}/sitemap.xml
`;
  fs.writeFileSync(dest, content);
}

function writeContentSettings(dir, values) {
  const dest = path.join(dir, 'src/content/settings.js');
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  const content = `/**
 * Local settings fallbacks
 *
 * These are the default settings used when Firebase CMS is not configured.
 */

export const settings = {
  site: {
    title: '${esc(values.projectName)}',
    description: '${esc(values.description)}',
    author: '${esc(values.orgName)}',
    url: '${esc(values.productionUrl)}',
  },
  seo: {
    defaultTitle: '${esc(values.projectName)}',
    defaultDescription: '${esc(values.description)}',
    keywords: [],
  },
};
`;
  fs.writeFileSync(dest, content);
}

function writeFirebaseRc(dir, values) {
  if (!values.firebaseProjectId) return;
  const content =
    JSON.stringify(
      { projects: { default: values.firebaseProjectId } },
      null,
      2,
    ) + '\n';
  fs.writeFileSync(path.join(dir, '.firebaserc'), content);
}

function writeTemplateState(dir) {
  const state = {
    setupComplete: true,
    setupAt: new Date().toISOString(),
    templateVersion: 'transpiled-web-template',
  };
  fs.writeFileSync(
    path.join(dir, '.template-state.json'),
    JSON.stringify(state, null, 2) + '\n',
  );
}

module.exports = {
  writeProjectConfig,
  writePackageJson,
  writeEnvExample,
  writeManifest,
  writeRobotsTxt,
  writeContentSettings,
  writeFirebaseRc,
  writeTemplateState,
};
